variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
dummy:
  stage: deploy
  only:
    variables:
      - $FOO == "bar"
  script:
    - echo
stages:
  - deploy
