set(_CATKIN_CURRENT_PACKAGE "genpy")
set(genpy_VERSION "0.6.8")
set(genpy_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(genpy_PACKAGE_FORMAT "1")
set(genpy_BUILD_DEPENDS "genmsg")
set(genpy_BUILD_EXPORT_DEPENDS "genmsg" "python-yaml")
set(genpy_BUILDTOOL_DEPENDS "catkin")
set(genpy_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(genpy_BUILDTOOL_EXPORT_DEPENDS )
set(genpy_EXEC_DEPENDS "genmsg" "python-yaml")
set(genpy_RUN_DEPENDS "genmsg" "python-yaml")
set(genpy_TEST_DEPENDS )
set(genpy_DOC_DEPENDS )
set(genpy_URL_WEBSITE "")
set(genpy_URL_BUGTRACKER "https://github.com/ros/genpy/issues")
set(genpy_URL_REPOSITORY "https://github.com/ros/genpy")
set(genpy_DEPRECATED "")