int16 user
int16 pitch
int16 roll
int16 yaw
int16 throttle

int16 target_height
int16 current_height

string kordajad_throt

string kordajad_t_pitch
string kordajad_t_roll

string kordajad_f_pitch
string kordajad_f_roll

int16 angle_delta

int16 P_throt
int16 D_throt
int16 I_throt

int16 P_t_pitch
int16 D_t_pitch
int16 I_t_pitch

int16 P_t_roll
int16 D_t_roll
int16 I_t_roll

int16 P_f_pitch
int16 D_f_pitch
int16 I_f_pitch

int16 P_f_roll
int16 D_f_roll
int16 I_f_roll
